## 9-Qubit Error Correcting Code

In [ ]:
In this notebook, we introduce and apply the first full quantum code - and what makes quantum codes full.
We will see that the 3-qubit code is heavily related to this one. 
The goal is to display the extent of amenability for fixing various errors simultaneously

In [15]:
# Importing required libraries
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit, Aer, execute
from qiskit.visualization import plot_histogram
from qiskit import user_config
from qiskit.quantum_info import partial_trace
import numpy as np
import random
from qiskit.extensions import UnitaryGate

# Visualization of circuits: Initializing backend simulators
qasm_sim = Aer.get_backend('qasm_simulator')
sv_sim = Aer.get_backend('statevector_simulator')

# Setting mpl as default drawer
%env QISKIT_SETTINGS {}
user_config.set_config('circuit_drawer', 'mpl')



env: QISKIT_SETTINGS={}


In [14]:
# Pauli operator initialization
sigma_x = np.array([[0,1],[1,0]])
sigma_y = np.array([[0,1j],[-1j,0]])
sigma_z = np.array([[1,0],[0,-1]])
sigma_I = np.identity(2)
print('Below we show the Pauli Operators which can be used to describe any quantum gate on an individual qubit:')
print('Pauli-X: \n', sigma_x) 
print('Pauli-Y: \n', sigma_y)
print('Pauli-Z: \n', sigma_z)
print('Pauli-I: \n', sigma_I)

Below we show the Pauli Operators which can be used to describe any quantum gate on an individual qubit:
Pauli-X: 
 [[0 1]
 [1 0]]
Pauli-Y: 
 [[ 0.+0.j  0.+1.j]
 [-0.-1.j  0.+0.j]]
Pauli-Z: 
 [[ 1  0]
 [ 0 -1]]
Pauli-I: 
 [[1. 0.]
 [0. 1.]]


$|0\rangle_L = \frac{1}{\sqrt{8}} \left( |000\rangle + |111\rangle \right) \left( |000\rangle + |111\rangle \right) \left( |000\rangle + |111\rangle \right)$

$|1\rangle_L = \frac{1}{\sqrt{8}} \left( |000\rangle - |111\rangle \right) \left( |000\rangle - |111\rangle \right) \left( |000\rangle - |111\rangle \right)$



In [18]:
pip install matplotlib


Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip install graphvi

In [ ]:
from qiskit import user_config
%env QISKIT_SETTINGS {}
user_config.set_config('circuit_drawer', 'mpl')


In [ ]:
from qiskit import QuantumCircuit

# Create a quantum circuit
qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)

# Draw the circuit
qc.draw()
